start_ui <- function(id) {
  ns <- NS(id)

  bslib::layout_sidebar(

    # sidebar: instructions & input data ---------------------------------------
    sidebar = bslib::sidebar(
      title = "Instructions",

      # card to load input data ------------------------------------------------
      bslib::card(
        class = 'card-note',
        bslib::card_header(class = 'bg-secondary', 'Input data'),
        span("You can start a new submission from the dataframe of
             raw metadata inferred from images and ROXAS settings
             files with the", code('rxs2tria'), 'package, or continue by
             loading a partially completed metadata file.'),
       actionButton(ns("btn_input"), "Load input data")
      ),

      # show selected data source ----------------------------------------------
      hr(class = "hr-slim"),
      span(
        span('Source of shown data', style=paste("font-weight:bold; color:", prim_col)),
        htmlOutput(ns("file_status"))
      ),

      # Instructions -----------------------------------------------------------
      hr(class = "hr-slim"),
      tags$ol(
        class = 'custom-indent',
        tags$li("Check that the inferred structure, generated labels and
          extracted raw metadata shown on the right are as you expect them for
          your dataset.")
      ),
      hr(),
      tags$ol(
        class = 'custom-indent', start = 2,
        tags$li("If applicable, fill in the columns for bandwidth and early wood analysis in the table on the right.")
      ),

      #checkboxInput(ns("check_raw"), "Inferred structure and metadata are correct.", value = FALSE),

      # next button
      hr(),
      actionButton(ns('btn_next'), 'Next', icon = icon('angle-double-right'))
    ),

    # main content -------------------------------------------------------------
    h5('Overview of input metadata'),

    # WARNING that app is still under construction
    bslib::card(
      max_height = 150,
      bslib::card_header(icon("exclamation-triangle",
                              class = "me-2", style = "color: #69004F;"),
                         tags$b("Warning"), style = "color: black; background-color: #E0CCDB;"),
      bslib::card_body(
        "This is a preview of the app currently under active development.
        There is absolutely no warranty regarding the accuracy or completeness
        of the information provided. Features and data are subject to change,
        and some functionality may not work as expected at this stage."
      ),
      style = "border: 2px solid #69004F; background-color: #F7F2F6"
    ),

    # accordion ----------------------------------------------------------------
    bslib::accordion(
      open = c("Data structure", 'Metadata extracted from files'),

      # Tree of data structure -------------------------------------------------
      bslib::accordion_panel(
        title = "Data structure",
        tags$p("This data.tree (",
               icon("map-marker", lib = "glyphicon"), "site > ",
               icon("tree-conifer", lib = "glyphicon"), "tree > ",
               icon("bore-hole", lib = "font-awesome"), "woodpiece > ",
               icon("vial", lib = "font-awesome"), "slide > ",
               icon("picture", lib = "glyphicon"), "image) ",
               "visualises the inferred structure of the provided dataset.
               It includes the labels generated by the ", code("rxs2tria"), " package
               from the original image names to uniquely identify each component."),

        shinyTree::shinyTree(ns("tree"), theme="proton", checkbox = FALSE,
                             tie_selection = TRUE, # set to true to allow for filtering
                             whole_node = TRUE, three_state = TRUE,
                             wholerow = FALSE)
      ),

      # Raw extracted metadata table -------------------------------------------
      bslib::accordion_panel(
        title = "Metadata extracted from files",
        tags$p("This table shows all structure, settings and image metadata extracted
          from the raw files with the", code("rxs2tria"), "package."),
        tags$p("If available, fill in the information on", code("band_width"), "and",
               code("only_ew"), "(in case only EW cells were measured).",
               "Click and drag the blue square in the bottom right corner of a cell to use autofill."),
        conditionalPanel(
          condition = "output.roxas_data_available",
          hr(),
          checkboxGroupInput(
            inputId = ns("cols_meta"),
            label = "Select columns to display:",
            choices = c(
              "Structure columns" = "cols_structure",
              "Image metadata columns " = "cols_images",
              "Settings metadata columns " = "cols_settings",
              "Local file path columns" = "cols_paths"),
            selected = c("cols_structure", "cols_images", "cols_settings", "cols_paths"),
            inline = TRUE
          ),
          ns=NS(id)),

        # radioButtons(ns("str_cols"), "Choose how to display structure columns:",
        #              choices = c("Extracted base identifiers" = "base",
        #                          "Generated labels" = "labels"),
        #              selected = "base"),
        DT::DTOutput(ns("roxas_table"))
      )

    ), # end of accordion

    verbatimTextOutput(ns("testing")),
    br()
  ) # end of layout_sidebar

}

# # IF EXAMPLE RUN:
# # If example_run is TRUE, show example data options, otherwise, show the default inputs
# if (example_run){
#   card(
#     class = 'card-note',
#     card_header(
#       class = 'bg-secondary',
#       'Input data'),
#     span('Select and load a data source to start:'),
#     radioButtons(
#       inputId = ns("input_src_ex"),
#       label = "Example data",
#       choices = list(
#         "Start fresh from automatically extracted metadata" = "df_meta_env",
#         "Start from partially completed metadata file" = "df_meta_json"
#       ),
#       selected = character(0)
#     ),
#     span('Or upload your own data: [file inputs are deactivated in preview mode]'),
#     fileInput(
#       inputId = ns("file_input_ex"),
#       label = "Upload own file",
#       accept = c(".csv", ".json")
#     ),
#     actionButton(
#       inputId = ns("btn_load_input_ex"),
#       label = "Load data"
#     )
#   )
# # ELSE (STANDARD INPUT):
# } else {
#   card(
#     class = 'card-note',
#     card_header(
#       class = 'bg-secondary',
#       'Input data'),
#     radioButtons(
#       inputId = ns("input_src"),
#       label = "Choose a data source to start",
#       choices = list(
#         "Use df_meta available in R environment" = "df_meta_env",
#         "Use df_meta loaded from .csv" = "df_meta_csv",
#         "Use partially completed metadata contribution from .json" = "df_meta_json"
#       ),
#       selected = character(0)
#     ),
#     fileInput(
#       inputId = ns("file_input"),
#       label = "Upload file:",
#       accept = c(".csv", ".json") # TODO: allow only csv for df_meta_csv, only json for df_meta_json?
#     ),
#     actionButton(
#       inputId = ns("btn_load_input"),
#       label = "Load data"
#     )
#   )
# },

