start_ui <- function(id) {
  ns <- shiny::NS(id)

  bslib::layout_sidebar(

    # sidebar: instructions & input data ---------------------------------------
    sidebar = bslib::sidebar(
      title = "Instructions",

      # card to load input data ------------------------------------------------
      shiny::tags$p(
        "You can start a new submission from the raw ROXAS metadata collected
        into a", shiny::code('QWAimages'), "object, or continue editing a", 
        shiny::code('QWAmetadata'), "object. Load data either from file or from 
        the current R environment."),
       
      shiny::actionButton(ns("btn_input"), "Load input data", icon = shiny::icon('file-arrow-up')),

      bslib::card(
        class = 'card-note',
        bslib::card_header(
          class = 'bg-primary',
          shiny::span(shiny::icon("exclamation", style = "color: white"),'Note')),
        "For large datasets, allow some time for each tab to load."
      ),

      # show selected data source ----------------------------------------------
      shiny::hr(class = "hr-slim"),
      shiny::span(
        shiny::span('Source of shown data', style=paste("font-weight:bold; color:", prim_col)),
        shiny::htmlOutput(ns("file_status"))
      ),

      # Instructions -----------------------------------------------------------
      shiny::hr(class = "hr-slim"),
      shiny::tags$ol(
        class = 'custom-indent',
        shiny::tags$li("Check that the inferred structure, generated labels and
          extracted raw metadata shown on the right are as you expect them for
          your dataset.")
      ),
      shiny::hr(),
      shiny::tags$ol(
        class = 'custom-indent', start = 2,
        shiny::tags$li("If applicable, fill in the columns for bandwidth and early wood analysis in the table on the right.")
      ),

      #shiny::checkboxInput(ns("check_raw"), "Inferred structure and metadata are correct.", value = FALSE),

      # next button
      shiny::hr(),
      shiny::actionButton(ns('btn_next'), 'Next', icon = shiny::icon('angle-double-right'))
    ),

    # main content -------------------------------------------------------------
    shiny::h5('Overview of input metadata'),

    # accordion ----------------------------------------------------------------
    bslib::accordion(
      open = c("Data structure", 'Metadata extracted from files'),

      # Tree of data structure -------------------------------------------------
      bslib::accordion_panel(
        title = "Data structure",
        shiny::tags$p("This data.tree (",
               shiny::icon("map-marker", lib = "glyphicon"), "site > ",
               shiny::icon("tree-conifer", lib = "glyphicon"), "tree > ",
               shiny::icon("bore-hole", lib = "font-awesome"), "woodpiece > ",
               shiny::icon("vial", lib = "font-awesome"), "slide > ",
               shiny::icon("picture", lib = "glyphicon"), "image) ",
               "visualises the inferred structure of the provided dataset.
               It includes the labels generated by the ", shiny::code("rxs2tria"), " package
               from the original image names to uniquely identify each component."),

        shinyTree::shinyTree(ns("tree"), theme="proton", checkbox = FALSE,
                             tie_selection = TRUE, # set to true to allow for filtering
                             whole_node = TRUE, three_state = TRUE,
                             wholerow = FALSE)
      ),

      # Raw extracted metadata table -------------------------------------------
      bslib::accordion_panel(
        title = "Metadata extracted from files",
        shiny::tags$p("This table shows all structure, settings and image metadata extracted
          from the raw files with the", shiny::code("rxs2tria"), "package."),
        shiny::tags$p(
          "Most columns are read-only, except", shiny::code("comment"), ",", shiny::code("band_width"), "and",
          shiny::code("only_ew"), "(in case only EW cells were measured)."),
        shiny::tags$p(
          shiny::icon("info", class = "me-1"),
          "The tables in this app support Excel-like keyboard shortcuts (e.g. copy/paste with Ctrl+C / Ctrl+V).",
          "Or click and drag the blue square in the bottom right corner of a cell to use autofill."),
        shiny::conditionalPanel(
          condition = "output.roxas_data_available",
          shiny::hr(),
          shiny::checkboxGroupInput(
            inputId = ns("cols_meta"),
            label = "Select columns to display:",
            choices = c(
              "Structure columns" = "cols_structure",
              "Image metadata columns " = "cols_images",
              "Settings metadata columns " = "cols_settings",
              "Local file path columns" = "cols_paths"),
            selected = c("cols_structure", "cols_images", "cols_settings"),
            inline = TRUE
          ),
          ns=shiny::NS(id)),

        rhandsontable::rHandsontableOutput(ns("image_table")),
      )

    ), # end of accordion


    # shiny::verbatimTextOutput(ns("testing")), # debug
    shiny::br()
  ) # end of layout_sidebar

}
